language: python

python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install pytest-cov coveralls

before_script:
  - flake8 --show-source .

script:
  - py.test --cov=bab .

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
