language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install pytest-cov coveralls

script:
  - pytest

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
